import datetime	#it is used for verification of DOB
import random
class Branch():
    def __init__(self,branch):
        self.branch= branch

class Customer:
    def __init__(self,customerid,name,gender,DOB,pin,email,mobileno,address):
        self.customerid=customerid
        self.name=name
        self.gender=gender
        self.DOB=DOB
        self.pin=pin
        self.email=email
        self.mobileno=mobileno
        self.address=address
	
class Account:
    def __init__(self,customerid,accountid,accountbalance):
        self.customerid=customerid
        self.accountid= accountid
        self.accountbalance= accountbalance
    def deposit(self,amount):
        self.accountbalance+=amount
        return self.accountbalance
    def withdraw(self,amount):
        if self.accountbalance<amount:
            print("Insufficient Balance!!")
        elif (self.accountbalance>100000):
             print("Amount exceeds threshold.")
        else:
            self.accountbalance-=amount
            print("Transaction Successful!")
            return self.accountbalance
    def transfer(self,account2,amount):
        if self.accountbalance<amount:
            print("Insufficient Balance!!")
        else:
            self.accountbalance-=amount
            print("Balance in current account: ",self.accountbalance)
                      


class Transaction(object):		#to store transaction details
    def __init__(self,transactionid,accountid,date,time,amount):
        self.transactionid= transactionid	#this needs to be generated by bank
        self.accountid= accountid
        self.date= date
        self.time= time
        self.amount= amount

def date():                                             #current date and time for storing details
    a=datetime.datetime.now()
    return(a.date())
def time():
    c=datetime.datetime.now()
    return(c.time())


def transactionid():                                    #generating random transaction ids
    b=random.randint(1000,2000)
    return b


def invoice():
    global choice
    global customerid
    global accountid
    global accountbalance
    global amount                 #generation of the particular transaction invoice
    if choice=="deposit":
    
        date_invoice=date()
        time_invoice=time()
        print("                 DRAMD BANK                ")
        print("                   INVOICE                 ")
        print(date_invoice,time_invoice,sep="          ")
        print("Customerid: ",customerid)
        print("Accountid: ",accountid)
        print("Accountbalance: ",accountbalance)
        print("DEPOSITED : ",amount,"in the current account")
        print("Current Balance",deposit)
        
        print("                 THANK YOU                   ")
    elif choice=="withdraw":
    
        date_invoice=date()
        time_invoice=time()
        print("                 DRAMD BANK                ")
        print("                   INVOICE                 ")
        print(date_invoice,time_invoice,sep="          ")
        print("Customerid: ",customerid)
        print("Accountid: ",accountid)
        print("Accountbalance: ",accountbalance)
        print("WITHDRAWAL of : ",amount,"from the current account")
        print("Current Balance",withdraw)
        
        print("                 THANK YOU                   ")
    elif choice=="transfer":
        
        global account2
        date_invoice=date()
        time_invoice=time()
        print("                 DRAMD BANK                ")
        print("                   INVOICE                 ")
        print(date_invoice,time_invoice,sep="          ")
        print("Customerid: ",customerid)
        print("Accountid: ",accountid)
        print("Accountbalance: ",accountbalance)
        print("TRANSFERED : ",amount,"to account: ",account2)
        print("Current Balance",transfer)
       
        print("                 THANK YOU                   ")



Customer.C1 = (1004,"Meraaj Akhtar Faruqui","M’","07/07/1998",1009,"meraajakhtar@gmail.com",87654398,"25 Jurong Avenue Block 897")

Customer.C2 = (1001,"Devansh Shah","M","13/09/2000",1241,"devanshshah@gmail.com",90810987,"50 Choa Chu Kang North 8")

Customer.C3 = (1002,"Akash Chandrasekar","M","18/01/2001",1111,"akashc@gmail.com",90909090,"54 Yew Tee Circle")

Customer.C4 = (1003,"Raman Gupta","M","09/09/1999",1234,"ramangupta@gmail.com",89796787,"27 Punggol Field Walk")

Customer.C5 = (1005,"Dheeptha Rajesh","F","07/07/1998",1049,"dheeptharajesh@gmail.com",90987878,"25 Boon Lay Avenue Block 107")

Account.A1=(1001,10001,15000)
Account.A2=(1002,10002,150000)
Account.A3=(1003,10003,23000)
Account.A4=(1004,10004,11000)
Account.A5=(1005,10005,17550)

Listofcustomers=[Customer.C1,Customer.C2,Customer.C3,Customer.C4,Customer.C5]
ListofAccounts=[Account.A1,Account.A2,Account.A3,Account.A4,Account.A5]



		
print("Welcome to DRAMD Bank ")
print()
while True:
    ask= input("Do you have an existing Bank Account(Yes)? To create one enter No: ")
    print("To exit the program type ‘Quit’.")
    if ask== "No" or ask == "no":
        print("Create your new account here!")
        name= input("Enter your full name: ")
        gender= input("Enter your Gender(M/F): ")
        if not (gender == "M" or gender == "F"):
            while True:
                print("Please enter a valid gender(M/F)")
                gender= input("Enter your Gender(M/F): ")
                if(gender == "M" or gender == "F"):
                    break
        DOB=int(input("Enter your DOB (DDMMYYYY): "))
        if len(str(DOB))!=8 and int(str(DOB)[2:4])>12 and int(str(DOB)[0:2])>31 and int(str(DOB)[4:8])-(datetime.datetime.now().year)<18:
            while True:
                print("Please enter a valid DOB")
                DOB= int(input("Enter your DOB(DDMMYYYY): "))
                if not(len(str(DOB))!=8 and int(str(DOB)[2:4])>12 and int(str(DOB)[0:2])>31) and int(str(DOB)[4:8])-datetime.datetime.now().year<18:
                    break

        pin= int(input("Enter your 4 digit pin: "))
        if len(str(pin)) != 4 and str(pin).isdigit == False :
            while True:
                print("Please enter a valid pin")
                pin= int(input("Enter your 4 digit pin: "))
                if len(str(pin)) == 4 and str(pin).isdigit == True:
                    break      
        pin1= int(input("Please enter your 4 digit pin once more: "))
        if pin1!=pin:
            while True:
                print("Pin entered doesn't match, please re-enter: ")
                pin= int(input("Enter your 4 digit pin: "))
                if len(str(pin1)) == 4 and str(pin1).isdigit == True and pin1==pin:
                    break	
        email= input("Enter your email address: ")
        if email.find("@") == -1:		# email.find(‘.com’) == -1,email may be .sg
            while True:
                print("Please enter a valid email address")
                email= input("Enter your email address: ")
                if  email.find("@") != -1:
                    break
        mobileno= input("Enter your mobile number: ")
        if len(mobileno) !=8 or mobileno.isdigit == False:
            while True:
                print("Please enter a valid mobile number")
                mobileno= int(input("Enter your mobile number: "))
                if not(len(mobileno) !=8 or mobileno.isdigit == False):
                    break
        address= input("Enter your address: ")
        accountbalance=int(input("Enter amount you would like to deposit: "))
        print("Your bank account has successfully been created")
        customerid=1000+ len(Listofcustomers)
        accountid=10000+len(ListofAccounts)
        c= Customer(customerid,name,gender,DOB,pin,email,mobileno,address)
        a= Account(customerid,accountid,accountbalance)
        Listofcustomers.append(c)
        ListofAccounts.append(a)
        
        print("Your customer id is:", 1000 + len(Listofcustomers))
        
        print("Your account id is:", 10000 + len(ListofAccounts))

        
        

    elif ask == "Yes" or "yes":
        customerid=int(input("Enter Customer ID: "))
        if(customerid<1000):
            while True:
                print("Please enter a valid Customer ID")
                customerid=int(input("Enter Customer ID: "))
                if(customerid>1000):
                   break
        accountid= int(input("Enter Account ID: "))
        if(accountid<10000):
            while True:
                print("Please enter a valid Account ID")
                accountid= int(input("Enter Account ID: "))
                if(accountid>10000):
                    break
        accountbalance=int(input("enter your current account balance: "))
        acc=Account(customerid,accountid,accountbalance)
        print("Enter 'deposit' for depositing into your current account")
        print("Enter 'withdraw' for withdrawal from your current account")
        print("Enter 'store' to store your current transaction details")
        print("Enter 'transfer' to transfer money from your current account")
        choice=input("Please enter the required transaction type: ")
        if choice=="deposit":
            amount=int(input("Enter the amount you wish to deposit: "))
            deposit=acc.deposit(amount)
        elif choice=="withdraw":
            amount=int(input("Enter the amount you wish to withdraw: "))
            withdraw=acc.withdraw(amount)
        elif choice=="transfer":
            account2=int(input("enter the accountid of the account you wish to transfer to"))
            amount=int(input("enter the amount you wish to transfer: "))
            transfer=acc.transfer(account2,amount)
        elif choice=="store":
            date=date()
            time=time()
            transactionid=transactionid()
            amount=int(input("Enter the transaction amount: "))
            transaction=Transaction(transactionid,accountid,date,time,amount)
            display=input("Do you wish to display the transaction details? Yes / No")
            while True:
                if display=="Yes" or display=="yes":
                    print("Transaction id: ",transactionid)
                    print("Account id: ",accountid)
                    print("Date of transaction: ",date)
                    print("Time of transaction: ",time)
                    print("Transaction amount: ",amount)
                    break
    
                             
    elif ask=="Quit" or  ask=="quit":
        print("Your invoice will be generated now")
        invoice()
        break
